if isunix
    delete *.mexw64
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        reconstruction_LLS1.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -lmwlapack reconstruction_LLS2.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -lmwlapack reconstruction_LLS3.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -lmwlapack reconstruction_T1WENO.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -lmwlapack stencil_centered.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -lmwlapack stencils_T1WENO.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -lmwlapack vandermonde_from_stencil_order3.cpp
else
    delete *.mexa64
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        reconstruction_LLS1.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -L'C:\Program Files\MATLAB\R2020b\extern\lib\win64\mingw64' ...
        -lmwlapack reconstruction_LLS2.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -L'C:\Program Files\MATLAB\R2020b\extern\lib\win64\mingw64' ...
        -lmwlapack reconstruction_LLS3.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -L'C:\Program Files\MATLAB\R2020b\extern\lib\win64\mingw64' ...
        -lmwlapack reconstruction_T1WENO.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -L'C:\Program Files\MATLAB\R2020b\extern\lib\win64\mingw64' ...
        -lmwlapack stencil_centered.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -L'C:\Program Files\MATLAB\R2020b\extern\lib\win64\mingw64' ...
        -lmwlapack stencils_T1WENO.cpp
    mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
        CXXLIBS='$CXXLIBS' ...
        CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
        LDFLAGS='$LDFLAGS -fopenmp' ...
        -L'C:\Program Files\MATLAB\R2020b\extern\lib\win64\mingw64' ...
        -lmwlapack vandermonde_from_stencil_order3.cpp
end
