mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
    CXXLIBS='$CXXLIBS' ...
    CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
    LDFLAGS='$LDFLAGS -fopenmp' ...
    reconstruction_LLS1.cpp

mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
    CXXLIBS='$CXXLIBS' ...
    CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
    LDFLAGS='$LDFLAGS -fopenmp' ...
    reconstruction_LLS2_naive.cpp -lmwlapack

mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
    CXXLIBS='$CXXLIBS' ...
    CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
    LDFLAGS='$LDFLAGS -fopenmp' ...
    reconstruction_LLS2.cpp -lmwlapack

mex -R2018a CXXFLAGS='$CXXFLAGS -Wall -fopenmp' ...
    CXXLIBS='$CXXLIBS' ...
    CXXOPTIMFLAGS='$CXXOPTIMFLAGS -O3 -march=native' ...
    LDFLAGS='$LDFLAGS -fopenmp' ...
    reconstruction_LLS3.cpp -lmwlapack
